with for
hello iteration: 0, thread: 0
hello iteration: 0, thread: 0
hello iteration: 0, thread: 0
hello iteration: 0, thread: 0
hello iteration: 0, thread: 0
hello iteration: 0, thread: 0
hello iteration: 0, thread: 0
hello iteration: 0, thread: 0
hello iteration: 0, thread: 0
hello iteration: 0, thread: 0
hello iteration: 1, thread: 0
hello iteration: 1, thread: 0
hello iteration: 1, thread: 0
hello iteration: 1, thread: 0
hello iteration: 1, thread: 0
hello iteration: 1, thread: 0
hello iteration: 1, thread: 0
hello iteration: 1, thread: 0
hello iteration: 1, thread: 0
hello iteration: 1, thread: 0
hello iteration: 2, thread: 0
hello iteration: 2, thread: 0
hello iteration: 2, thread: 0
hello iteration: 2, thread: 0
hello iteration: 2, thread: 0
hello iteration: 2, thread: 0
hello iteration: 2, thread: 0
hello iteration: 2, thread: 0
hello iteration: 2, thread: 0
hello iteration: 2, thread: 0
hello iteration: 3, thread: 0
hello iteration: 3, thread: 0
hello iteration: 3, thread: 0
hello iteration: 3, thread: 0
hello iteration: 3, thread: 0
hello iteration: 3, thread: 0
hello iteration: 3, thread: 0
hello iteration: 3, thread: 0
hello iteration: 3, thread: 0
hello iteration: 3, thread: 0
hello iteration: 4, thread: 0
hello iteration: 4, thread: 0
hello iteration: 4, thread: 0
hello iteration: 4, thread: 0
hello iteration: 4, thread: 0
hello iteration: 4, thread: 0
hello iteration: 4, thread: 0
hello iteration: 4, thread: 0
hello iteration: 4, thread: 0
hello iteration: 4, thread: 0
hello iteration: 5, thread: 0
hello iteration: 5, thread: 0
hello iteration: 5, thread: 0
hello iteration: 5, thread: 0
hello iteration: 5, thread: 0
hello iteration: 5, thread: 0
hello iteration: 5, thread: 0
hello iteration: 5, thread: 0
hello iteration: 5, thread: 0
hello iteration: 5, thread: 0
hello iteration: 6, thread: 0
hello iteration: 6, thread: 0
hello iteration: 6, thread: 0
hello iteration: 6, thread: 0
hello iteration: 6, thread: 0
hello iteration: 6, thread: 0
hello iteration: 6, thread: 0
hello iteration: 6, thread: 0
hello iteration: 6, thread: 0
hello iteration: 6, thread: 0
hello iteration: 7, thread: 0
hello iteration: 7, thread: 0
hello iteration: 7, thread: 0
hello iteration: 7, thread: 0
hello iteration: 7, thread: 0
hello iteration: 7, thread: 0
hello iteration: 7, thread: 0
hello iteration: 7, thread: 0
hello iteration: 7, thread: 0
hello iteration: 7, thread: 0
hello iteration: 8, thread: 0
hello iteration: 8, thread: 0
hello iteration: 8, thread: 0
hello iteration: 8, thread: 0
hello iteration: 8, thread: 0
hello iteration: 8, thread: 0
hello iteration: 8, thread: 0
hello iteration: 8, thread: 0
hello iteration: 8, thread: 0
hello iteration: 8, thread: 0
hello iteration: 9, thread: 0
hello iteration: 9, thread: 0
hello iteration: 9, thread: 0
hello iteration: 9, thread: 0
hello iteration: 9, thread: 0
hello iteration: 9, thread: 0
hello iteration: 9, thread: 0
hello iteration: 9, thread: 0
hello iteration: 9, thread: 0
hello iteration: 9, thread: 0

without for
hello iteration: 0, thread: 5
hello iteration: 0, thread: 0
hello iteration: 0, thread: 4
hello iteration: 0, thread: 3
hello iteration: 0, thread: 7
hello iteration: 0, thread: 1
hello iteration: 0, thread: 6
hello iteration: 0, thread: 9
hello iteration: 0, thread: 8
hello iteration: 0, thread: 2
hello iteration: 1, thread: 1
hello iteration: 1, thread: 6
hello iteration: 1, thread: 0
hello iteration: 1, thread: 7
hello iteration: 1, thread: 5
hello iteration: 1, thread: 4
hello iteration: 1, thread: 2
hello iteration: 1, thread: 3
hello iteration: 1, thread: 8
hello iteration: 1, thread: 9
hello iteration: 2, thread: 9
hello iteration: 2, thread: 0
hello iteration: 2, thread: 7
hello iteration: 2, thread: 5
hello iteration: 2, thread: 2
hello iteration: 2, thread: 3
hello iteration: 2, thread: 1
hello iteration: 2, thread: 4
hello iteration: 2, thread: 8
hello iteration: 2, thread: 6
hello iteration: 3, thread: 3
hello iteration: 3, thread: 7
hello iteration: 3, thread: 4
hello iteration: 3, thread: 2
hello iteration: 3, thread: 8
hello iteration: 3, thread: 6
hello iteration: 3, thread: 5
hello iteration: 3, thread: 0
hello iteration: 3, thread: 1
hello iteration: 3, thread: 9
hello iteration: 4, thread: 8
hello iteration: 4, thread: 6
hello iteration: 4, thread: 9
hello iteration: 4, thread: 5
hello iteration: 4, thread: 1
hello iteration: 4, thread: 2
hello iteration: 4, thread: 0
hello iteration: 4, thread: 7
hello iteration: 4, thread: 3
hello iteration: 4, thread: 4
hello iteration: 5, thread: 3
hello iteration: 5, thread: 4
hello iteration: 5, thread: 9
hello iteration: 5, thread: 6
hello iteration: 5, thread: 1
hello iteration: 5, thread: 0
hello iteration: 5, thread: 7
hello iteration: 5, thread: 5
hello iteration: 5, thread: 2
hello iteration: 5, thread: 8
hello iteration: 6, thread: 3
hello iteration: 6, thread: 6
hello iteration: 6, thread: 9
hello iteration: 6, thread: 4
hello iteration: 6, thread: 8
hello iteration: 6, thread: 5
hello iteration: 6, thread: 2
hello iteration: 6, thread: 0
hello iteration: 6, thread: 7
hello iteration: 6, thread: 1
hello iteration: 7, thread: 9
hello iteration: 7, thread: 8
hello iteration: 7, thread: 1
hello iteration: 7, thread: 6
hello iteration: 7, thread: 5
hello iteration: 7, thread: 2
hello iteration: 7, thread: 0
hello iteration: 7, thread: 7
hello iteration: 7, thread: 3
hello iteration: 7, thread: 4
hello iteration: 8, thread: 9
hello iteration: 8, thread: 6
hello iteration: 8, thread: 5
hello iteration: 8, thread: 2
hello iteration: 8, thread: 8
hello iteration: 8, thread: 0
hello iteration: 8, thread: 7
hello iteration: 8, thread: 1
hello iteration: 8, thread: 4
hello iteration: 8, thread: 3
hello iteration: 9, thread: 9
hello iteration: 9, thread: 0
hello iteration: 9, thread: 4
hello iteration: 9, thread: 2
hello iteration: 9, thread: 8
hello iteration: 9, thread: 1
hello iteration: 9, thread: 3
hello iteration: 9, thread: 7
hello iteration: 9, thread: 5
hello iteration: 9, thread: 6